# Generated by Django 3.0.5 on 2020-04-29 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20200425_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 23, 11, 51, 858739, tzinfo=utc), verbose_name='Data'),
        ),
    ]
